Feat/pn 12583 - Make Public Keys CRUD operations available to FE
pagopa/pn-bff pull request #114
Opened 2024-09-18 12:07 UTC by mflauti

## Short description

This PR wraps BE microservices making them available to FE. It refers to Jira tasks from PN-12583 to, PN-12587.

## List of changes proposed in this pull request
- Public key creation
- Public key rotation
- Public keys list
- Public key activation/block
- Public key deletion
- Public keys mocks defiition
- Public keys client tests

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-09-19 13:01 UTC, AndreaCimini90 requested changes
Mapper test suites are missed

2024-09-24 07:46 UTC, AndreaCimini90 approved these changes

2024-09-24 16:43 UTC, AndreaCimini90 approved these changes

2024-09-26 09:32 UTC, AndreaCimini90 requested changes

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/mappers/publickeys/PublicKeysCheckIssuerStatusMapper.java
> +    default BffPublicKeysCheckIssuerResponse mapPublicKeysIssuerStatus(PublicKeysIssuerResponse publicKeysIssuerResponse, @Context Consent consent) {
add java doc to all the methods of the mapper

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/mappers/publickeys/PublicKeysIssuerStatusMapper.java
> +package it.pagopa.pn.bff.mappers.publickeys;
This can be removed

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mappers/publickeys/PublicKeysIssuerStatusMapperTest.java
> +package it.pagopa.pn.bff.mappers.publickeys;
This can be removed

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mocks/PublicKeysMock.java
> +    private ArrayList<String> getPublicKeyGroups(String... groups) { return new ArrayList<>(Arrays.asList(groups)); }
this can be removed

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mocks/PublicKeysMock.java
> +import it.pagopa.pn.bff.generated.openapi.msclient.user_attributes.model.Consent;
this can be removed

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mocks/PublicKeysMock.java
> +import it.pagopa.pn.bff.generated.openapi.msclient.user_attributes.model.ConsentType;
this can be removed

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mocks/PublicKeysMock.java
> +    public BffPublicKeysCheckIssuerResponse getNullCheckIssuerMock() {
this can be removed

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/mappers/publickeys/PublicKeysCheckIssuerStatusMapper.java
> +}
we can avoid to define the PublicKeysIssuerStatusMapper and we can do all the transformations here. Follow this steps:

1. remove the default and the body from mapPublicKeysCheckIssuerStatus
2. remove the `@Context`
3. use the `@Mapping` annotation (check map struct guide)
4. use the qualifiedByName and `@Named` annotation to map the tosAccepted key (check map struct guide)

TIPS: with `@Mapping` we can map a source object into a target object. With this we can map the micro-service publicKeysIssuerResponse into issuer. With `@Mapping`, qualifiedByName and `@Named` we can do the calculation to map the micro-service consent into tosAccepted.

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/service/PublicKeysPgService.java
> +        .map(PublicKeysIssuerStatusMapper.modelMapper::mapPublicKeysIssuerStatus);
removing the mapper, the PublicKeysIssuerResponse import must be changed from the bff one to the micro-service one

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mappers/publickeys/PublicKeysCheckIssuerStatusMapperTest.java
> +        Consent consent = new Consent();
we can remove the = new Consent()

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mappers/publickeys/PublicKeysCheckIssuerStatusMapperTest.java
> +public class PublicKeysCheckIssuerStatusMapperTest {
the public identifier can be removed. Do it for all the tests

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mappers/publickeys/PublicKeysCheckIssuerStatusMapperTest.java
> +        assertThat(bffPublicKeysCheckIssuerResponse).usingRecursiveComparison().isEqualTo(publicKeysMock.getNullCheckIssuerMock());
Changing the mapper, we can remove the `usingRecursiveComparison` and the  `publicKeysMock.getNullCheckIssuerMock()`. Now we have to check if the result is null

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/pnclient/apikeys/PnPublicKeyManagerClientPGImplTest.java
> +    void getIssuerStatusPublicKeysError() {
rename with check...

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/pnclient/apikeys/PnPublicKeyManagerClientPGImplTestIT.java
> +    void getIssuerStatusPublicKeys() throws JsonProcessingException {
rename with check...

2024-09-26 09:32 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/pnclient/apikeys/PnPublicKeyManagerClientPGImplTestIT.java
> +    void getIssuerStatusPublicKeysError() {
rename with check...

2024-09-26 10:21 UTC, mflauti commented on src/main/java/it/pagopa/pn/bff/mappers/CxTypeMapper.java
> +    it.pagopa.pn.bff.generated.openapi.msclient.user_attributes.model.CxTypeAuthFleet convertUserAttributesPGCXType(it.pagopa.pn.bff.generated.openapi.server.v1.dto.apikeys.CxTypeAuthFleet cxType);
the convertUserAttributesCXType already exists but converts the user-attributes CxType from server to client. Here we need to convert the apikeys server to user-attributes client

2024-09-27 10:14 UTC, AndreaCimini90 approved these changes

2024-09-27 10:54 UTC, merged