PN-13041: additional languages in schema
pagopa/pn-bff pull request #138
Opened 2024-10-28 08:40 UTC by fbianchicodermine

## Short description

Add additional languages in new notification schema

## List of changes proposed in this pull request

- Update version of `pn-delivery` service in `pom`

2024-10-30 14:46 UTC, alessandrogelmi requested changes

2024-10-30 14:46 UTC, alessandrogelmi commented on docs/openapi/notification-schemas/notification.yaml
> +            maxItems: 1
Add a description

2024-10-30 14:46 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/mappers/notifications/NewSentNotificationMapper.java
>       * @return the mapped NewNotificationRequestV23
Update java doc

2024-10-30 14:46 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/mappers/notifications/NotificationSentDetailMapper.java
>       * @param notification the FullSentNotificationV24 to map
Update java doc

2024-10-30 15:45 UTC, alessandrogelmi approved these changes

2024-11-04 17:02 UTC, alessandrogelmi requested changes
Merge develop into this PR in order to take the updated commit id of pn-delivery

2024-11-05 14:25 UTC, AndreaCimini90 approved these changes

2024-11-05 14:42 UTC, AndreaCimini90 approved these changes

2024-11-05 14:45 UTC, merged