PN-9830 - Notification detail mapper
pagopa/pn-bff pull request #15
Opened 2024-02-19 14:30 UTC by alessandrogelmi

2024-03-01 14:42 UTC, AndreaCimini90 requested changes
Two change requests that are about all the code.
- write java doc
- in the tests, use assertTrue, assertFalse and ecc... instead of the simple assert

2024-03-01 14:42 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mapper/NotificationDetailMapperTest.java
>      void testMapNotificationDetail() {
For this and below test use a most speaking name

2024-03-01 14:42 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/utils/notificationDetail/NotificationDetailUtilityTest.java
> +        assert calculatedParsedNotification.getOtherDocuments().get(0).equals(
for this condition and below, separate the assert from the object that is asserted

2024-03-01 14:42 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/utils/notificationDetail/NotificationDetailUtilityTest.java
> +                        .findFirst()
Same as for others combination of filter and findFirst. Check all the occurrences

2024-03-01 14:42 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/utils/notificationDetail/PopulateMacroStepsTest.java
> +package it.pagopa.pn.bff.utils.notificationDetail;
Same considerations done in the previous tests

2024-03-04 13:22 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/mapper/NotificationElementMapper/SenderNotificationTimelineMapper.java
> +    RecipientNotificationTimelineMapper paTimelineMapper = Mappers.getMapper(RecipientNotificationTimelineMapper.class);
This is the mapper of timeline. Because it has `hidden` and `index`

2024-03-04 13:36 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/utils/notificationDetail/NotificationDetailUtility.java
> +                .filter(el -> el.getCategory() == TimelineCategory.NOTIFICATION_CANCELLED)
and how can i know if there's a NOTIFICATION_CANCELLED or NOTIFICATION_CANCELLATION_REQUEST timeline category?

2024-03-04 13:50 UTC, alessandrogelmi commented on docs/openapi/notificationDetailSchemas/notification-enums.yaml
> +    PhysicalCommunicationType:
Some enums are not exported from pn-delivery/pn-delivery-push. Others (Like NotificationStatus) we have to add some values

2024-03-04 14:24 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/utils/notificationDetail/NotificationDetailUtility.java
> +                .filter(el -> el.getCategory() == TimelineCategory.NOTIFICATION_CANCELLED)
Ok there was a misunderstanding. It's not possibile to use `find` directly. We have to `filter` and then use `findFirst`

2024-03-04 14:37 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/utils/notificationDetail/NotificationDetailUtility.java
> +                    .map(t -> {
I've used a for loop

2024-03-05 09:57 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/mapper/NotificationElementMapper/SenderNotificationTimelineMapper.java
> +    RecipientNotificationTimelineMapper paTimelineMapper = Mappers.getMapper(RecipientNotificationTimelineMapper.class);
but it is for PA

2024-03-05 09:59 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/mapper/NotificationDetailMapper.java
>  import it.pagopa.pn.bff.generated.openapi.msclient.delivery_pa.model.FullSentNotificationV23;
check package naming convention. i remember that packages name aren't in camel case

2024-03-05 13:27 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/mapper/NotificationElementMapper/SenderNotificationTimelineMapper.java
> +    RecipientNotificationTimelineMapper paTimelineMapper = Mappers.getMapper(RecipientNotificationTimelineMapper.class);
Ah ok, it was a copy/paste error

2024-03-07 14:33 UTC, AndreaCimini90 approved these changes

2024-03-07 14:34 UTC, merged