PN-5210 - Setup of PN-BFF
pagopa/pn-bff pull request #4
Opened 2024-01-23 11:32 UTC by alessandrogelmi

2024-01-24 12:03 UTC, AndreaCimini90 requested changes
Check all the code that is releated to safestorage (also the yml files) and remove it if it is useless

2024-01-24 12:03 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/middleware/externalclient/pnclient/safestorage/PnSafeStorageClient.java
> +package it.pagopa.pn.bff.middleware.externalclient.pnclient.safestorage;
Is this needed for some reason?

2024-01-25 08:42 UTC, alessandrogelmi commented on src/main/java/it/pagopa/pn/bff/middleware/externalclient/pnclient/safestorage/PnSafeStorageClient.java
> +package it.pagopa.pn.bff.middleware.externalclient.pnclient.safestorage;
removed

2024-01-25 08:58 UTC, AndreaCimini90 approved these changes

2024-01-25 09:13 UTC, AndreaCimini90 approved these changes

2024-01-25 09:14 UTC, merged