PN-10950-be-api-exchange-qr-code-pf-pg
pagopa/pn-bff pull request #53
Opened 2024-05-14 12:26 UTC by ImJimMoriarty

This PR introduces a proxy for the aar_qr_check in selfcare.

2024-05-16 06:17 UTC, AndreaCimini90 requested changes

2024-05-16 06:17 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mocks/NotificationsReceivedMock.java
> +    public ResponseCheckAarMandateDto getResponseCheckAarMandateDtoPNMock(){
add an empty line

2024-05-16 06:17 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mocks/NotificationsReceivedMock.java
> +    public BffRequestCheckAarMandateDto getRequestCheckAarMandateDtoPNMock(){
add an empty line

2024-05-16 10:47 UTC, ImJimMoriarty commented on docs/openapi/api-internal-pn-bff-recipient-notifications.yaml
> +        content:
it is already present below

2024-05-16 13:54 UTC, AndreaCimini90 requested changes

2024-05-16 13:54 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/mappers/notifications/NotificationAarQrCodeMapper.java
> +public interface NotificationAarQrCodeMapper {
Add java doc here

2024-05-16 13:54 UTC, AndreaCimini90 commented on src/test/java/it/pagopa/pn/bff/mappers/notifications/NotificationsReceivedMapperTest.java
> +    @Test
Move this and test below in a new file

2024-05-16 14:55 UTC, AndreaCimini90 submitted a review, later dismissed

2024-05-17 07:02 UTC, AndreaCimini90 approved these changes

2024-05-17 07:33 UTC, merged