Feature/pn 10908
pagopa/pn-bff pull request #64
Opened 2024-05-23 12:31 UTC by Vallasc

## Short description

Added SenderDashboard API

## List of changes proposed in this pull request

- Added SenderDashboard API

## How to test

The endpoint `/bff/v1/sender-dashboard/dashboard-data-request/{cxType}/{cxId}` should return notification data.

2024-05-27 07:09 UTC, AndreaCimini90 requested changes

2024-05-27 07:09 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/service/senderdashboard/SenderDashboardService.java
> +                        PnBffExceptionCodes.ERROR_CODE_PN_GENERIC_ERROR
I'm not sure about the use of PnBffExceptionCodes.ERROR_CODE_PN_GENERIC_ERROR here and for the others errors below. The use of this error code is discouraged. Check the other micro-services to see how they manage similar cases

2024-05-27 08:37 UTC, Vallasc commented on docs/openapi/api-internal-pn-bff-sender-dashboard.yaml
> +        - $ref: './sender-dashboard-schemas/sender-dashboard.yaml#/components/parameters/BffSenderDashboardPathCxType'
The parameters BffSenderDashboardPathCxType and BffSenderDashboardPathCxId are included both as path parameters and in the header to facilitate API Gateway caching.

2024-05-27 13:53 UTC, vincenzo-racca-pa requested changes

2024-05-27 13:53 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/bff/config/JacksonConfig.java
> +    public ObjectMapper objectMapper() {
Invece di sovrascrivere l'ObjectMapper creare due classi distinte, una che mappa la response di DataLake e una dedicata alla response del FE.

2024-05-27 13:53 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/bff/rest/SenderDashboardController.java
> +        log.logStartingProcess("getDashboardDataV1");
I log di process vengono automaticamente applicati dall'Aspect di pn-commons, per cui possiamo eliminarli.

2024-05-27 13:53 UTC, vincenzo-racca-pa commented on pom.xml
> +        <aws.java.sdk.version>2.25.52</aws.java.sdk.version>
Cancellare la versione e il bom di aws così da importare quello di pn-commons. Inoltre cancellare la versione di lombok così da prendere la versione di Spring.

2024-05-28 05:57 UTC, AndreaCimini90 requested changes

2024-05-28 05:57 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/bff/service/senderdashboard/resources/DatalakeS3Resource.java
> +public class DatalakeS3Resource {
Can we call the mapper inside the service? I think that is better that this client returns the Datalake DTO instead of the Bff one

2024-05-28 11:00 UTC, AndreaCimini90 approved these changes

2024-05-28 12:31 UTC, merged