[PN-11373] Added DeleteOldVersionsForRaddStoreRegistry Rules in IndexesBucket LifecycleConfiguration
pagopa/pn-bff pull request #68
Opened 2024-05-28 13:21 UTC by flaminiaScarciofolo

## Short description

Include a summary of the changes.

## List of changes proposed in this pull request

- Added DeleteOldVersionsForRaddStoreRegistry Rules in IndexesBucket LifecycleConfiguration

## How to test

Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-05-29 07:41 UTC, AndreaCimini90 requested changes

2024-05-29 07:41 UTC, AndreaCimini90 commented on scripts/aws/cfn/storage.yml
> +          - Id: DeleteOldVersionsForRaddStoreRegistry
Cambierei il nome del bucket in `!Sub ${ProjectName}-bff-data-${AWS::Region}-${AWS::AccountId}` e il `Prefix: indexes/` in `Prefix: sender-dashboard/indexes/`. Se viene fatta questa modifica, va cambiato il valore di PnIndexObjectKey in microservice-dev-cfg.json

2024-05-29 09:24 UTC, fdammassa submitted a review, later dismissed

2024-05-29 12:58 UTC, AndreaCimini90 requested changes

2024-05-29 12:58 UTC, AndreaCimini90 commented on scripts/aws/cfn/storage.yml
> +  BffBucketBucket:
Cambiare BffBucketBucket in BffBucket

2024-05-29 12:58 UTC, AndreaCimini90 commented on scripts/aws/cfn/storage.yml
> +  BffBucketArn:
Aggiornare IndexesBucketArn, IndexesBucketName e IndexesBucketRegion con in nuovi nomi anche dentro microservice.yml

2024-05-30 08:19 UTC, AndreaCimini90 approved these changes

2024-05-30 15:19 UTC, merged