[PN-11337] Feat: Added lambda function for radd store registry in microservice.yml
pagopa/pn-bff pull request #69
Opened 2024-05-28 13:55 UTC by flaminiaScarciofolo

## Short description

We have to create new Lambda Function to generate radd store registry csv files.

## List of changes proposed in this pull request

- Added lambda function for radd store registry in microservice.yml

## How to test

Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-05-29 08:51 UTC, masciale89 commented on scripts/aws/cfn/microservice.yml
> +        - PolicyName: AccessIndexesBucket
cambiamo il nome della policy in accordo con l'uso del bucket

2024-05-29 08:52 UTC, masciale89 commented on scripts/aws/cfn/microservice.yml
> +                  - !Sub ${IndexesBucketArn}/${IndexesBucketRaddStoreRegistryPrefix}/*
cambiamo il nome della variabile in accordo con il cambio del nome del bucket

2024-05-29 08:53 UTC, masciale89 requested changes
cambiare i nomi delle variabili in accordo con il cambio del nome del bucket di "versionamento"

2024-05-29 09:25 UTC, fdammassa requested changes

2024-05-29 09:25 UTC, fdammassa commented on scripts/aws/cfn/storage.yml
> +    Value: RaddStoreRegistryLambda
@flaminiaScarciofolo l'output deve corrispondere al nome del LogGroupName `RaddStoreRegistryLambdaLogGroup`

2024-06-03 06:51 UTC, AndreaCimini90 approved these changes

2024-06-03 06:56 UTC, merged